version: '3.3'

services:

  david:
    build: .
    image: ralphg6/david
    network_mode: bridge
    ports:
      - 6006:6006
      - 8888:8888
    volumes:
      - ./notebooks/input:/notebooks/input
      - ./notebooks/output:/notebooks/output
      - ./notebooks:/notebooks/inbuild

# volumes:
#   david-input:
#   david-output:

