# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="component.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\n\007io.dazu",
    serialized_pb=b"\n\x0f\x63omponent.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaf\x01\n\x0b\x44\x61zuMessage\x12&\n\x05input\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12'\n\x06output\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct2;\n\x10\x43omponentService\x12'\n\x07Process\x12\x0c.DazuMessage\x1a\x0c.DazuMessage\"\x00\x42\t\n\x07io.dazub\x06proto3",
    dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,],
)


_DAZUMESSAGE = _descriptor.Descriptor(
    name="DazuMessage",
    full_name="DazuMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="input",
            full_name="DazuMessage.input",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="context",
            full_name="DazuMessage.context",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="DazuMessage.data",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="output",
            full_name="DazuMessage.output",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=50,
    serialized_end=225,
)

_DAZUMESSAGE.fields_by_name[
    "input"
].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_DAZUMESSAGE.fields_by_name[
    "context"
].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_DAZUMESSAGE.fields_by_name[
    "data"
].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_DAZUMESSAGE.fields_by_name[
    "output"
].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name["DazuMessage"] = _DAZUMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DazuMessage = _reflection.GeneratedProtocolMessageType(
    "DazuMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _DAZUMESSAGE,
        "__module__": "component_pb2"
        # @@protoc_insertion_point(class_scope:DazuMessage)
    },
)
_sym_db.RegisterMessage(DazuMessage)


DESCRIPTOR._options = None

_COMPONENTSERVICE = _descriptor.ServiceDescriptor(
    name="ComponentService",
    full_name="ComponentService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=227,
    serialized_end=286,
    methods=[
        _descriptor.MethodDescriptor(
            name="Process",
            full_name="ComponentService.Process",
            index=0,
            containing_service=None,
            input_type=_DAZUMESSAGE,
            output_type=_DAZUMESSAGE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_COMPONENTSERVICE)

DESCRIPTOR.services_by_name["ComponentService"] = _COMPONENTSERVICE

# @@protoc_insertion_point(module_scope)
