# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dazu.components.proto.component_pb2 as component__pb2


class ComponentServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.Process = channel.unary_unary(
            "/ComponentService/Process",
            request_serializer=component__pb2.DazuMessage.SerializeToString,
            response_deserializer=component__pb2.DazuMessage.FromString,
        )


class ComponentServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Process(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ComponentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Process": grpc.unary_unary_rpc_method_handler(
            servicer.Process,
            request_deserializer=component__pb2.DazuMessage.FromString,
            response_serializer=component__pb2.DazuMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ComponentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
