OUTPUT_TEXT_ATTRIBUTE = "output_text"

TEXT_ATTRIBUTE = "text"

INTENTS_ATTRIBUTE = "intents"

ENTITIES_ATTRIBUTE = "entities"

CONTEXT_ATTRIBUTE = "context"

DEFAULT_DATA_PATH = "data"

DEFAULT_MODELS_PATH = "models"

DEFAULT_CONFIG_PATH = "config.yml"

TRAIN_DATA_FILE = "know.json"

DEFAULT_LOG_LEVEL = "INFO"

ENV_LOG_LEVEL = "LOG_LEVEL"

CONFIG_DEFAULT_ADAPTER = "default_adapter"
